dbt_mssql:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{env_var('ENV_DBT_SERVER')}}"
      port: "{{env_var('ENV_DBT_PORT') | int}}"
      database: "{{env_var('ENV_DBT_DATABASE')}}"
      schema: "{{env_var('ENV_DBT_SCHEMA')}}"
      user: "{{env_var('ENV_DBT_USER')}}"
      password: "{{env_var('ENV_DBT_PASSWORD')}}"
      threads: 1
    prod:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{env_var('ENV_DBT_SERVER')}}"
      port: "{{env_var('ENV_DBT_PORT') | int}}"
      database: "{{env_var('ENV_DBT_DATABASE')}}"
      schema: "{{env_var('ENV_DBT_SCHEMA')}}"
      user: "{{env_var('ENV_DBT_USER')}}"
      password: "{{env_var('ENV_DBT_PASSWORD')}}"
      threads: 1