debug: False

dbt:
  singleton: True
  target: dev
  project_dir: "./dbt"

log_storage: # Take first entry ONLY
  - entry:
    type: pickle
    path: C:/Temp/
  # - entry:
  #   type: mongodb #TODO
  #   uri: mongodb://localhost:27017
  #   collection: logs
  # - entry:
  #   type: sqlserver #TODO
  #   uri: tbu
  #   collection: logs