debug: False

dbt:
  singleton: True
  target: dev
  project_dir: "./dbt"

log_storage: # Take first entry ONLY
  - entry:
    type: sqlserver
    server: env_sqlserver_host
    port: 1433
    database: dbt
    user: env_sqlserver_secret_name
    password: env_sqlserver_secret_value
  - entry:
    type: pickle
    path: C:/Temp/