name: Awesome dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag tuiladat/awesome-dbt:$(date +%s) . -f ./.docker/awesome-dbt.dockerfile