name: Awesome dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file /services/api/service/Dockerfile --tag awesome-dbt-api:$(date +%s)
