name: SSH to server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-20.04

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mv dbt-mssql dbt-mssql-$(date +%s) > /dev/null
            git clone git@github.com:datnguye/dbt-mssql.git --branch release --config core.sshCommand="ssh -i ${{ secrets.SSH_KEY_PATH }}"

