name: SSH to server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-20.04

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone git@github.com:datnguye/dbt-mssql.git --config ${{ secrets.SSH_GIT_CLONE_CONFIG }}
            ${{ secrets.SSH_PASSPHRASE }}

