name: SSH deployment

on:
  pull_request:
    branches: [ unixrelease ]

jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mv dbt-mssql dbt-mssql-$(date +%s) > /dev/null
            git clone https://${{ secrets.GIHUB_ACTION_USER }}:${{ secrets.GIHUB_ACTION_TOKEN }}@github.com/datnguye/dbt-mssql.git
            
  install-ODBC:
    needs: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Install ODBC"
            
  install-enviroment:
    needs: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "create env for: install dbt and services"
            
  on-service:
    needs:
      - install-enviroment
      - install-ODBC
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "create service unit file"
            echo "create nginx file"
            echo "systemctl restart *.service"
            
            
